INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'david', 'Learn AWS Ceritified', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'david', 'Learn Java', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'david', 'Learn Javascript', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'david', 'Learn Python', CURRENT_DATE(), false);